### ISSUE TITLE
Fix poor styling on the website 

### ISSUE THREAD

**Issue by roshaan005** [avneesh0612/audible-clone#26]
**Describe the bug**
Whenever the website is opened on a phone there are two main issues that I came across 
1. The elements in the footer lose their responsiveness.
2. A few category names appear on the slideshow with barely visible font color.

**To Reproduce**
1. Go to the website on your phone 
2. Scroll down to to view each of the things. 

**Expected behavior**
the category names should be placed according to the design and the footer elements should be made responsive preferably by reducing the font size 

**Screenshots**
![Screenshot from 2021-09-29 15-46-15](https://user-images.githubusercontent.com/73021546/135254789-35e72c59-ba57-4512-a22d-bfa636316726.png)
![Screenshot from 2021-09-29 15-45-37](https://user-images.githubusercontent.com/73021546/135254818-c80c49c5-b9de-49a1-8cd9-0bcd7e0c3fee.png)

**Smartphone (please complete the following information):**
 - Device: iphone 8 plus 
 - OS: ios 
 - Browser:chrome
 - Version 93.0.4577.63

**Additional context**

**Comment by avneesh0612** [comment]
Okay, thanks for informing @roshaan005

**Comment by Anna719** [comment]
Hi! Can I work on this issue? Thanks :)

**Comment by avneesh0612** [comment]
Sure @Anna719

**Comment by avneesh0612** [comment]
hey @Anna719 are you still working?

**Comment by Anna719** [comment]
Hi, i saw that you closed the issue and everything was already fixed :)

**Comment by avneesh0612** [comment]
Um the issue is open and I haven't pushed something for that?

**Comment by avneesh0612** [comment]
Yup, the issue is there-
![image](https://user-images.githubusercontent.com/76690419/143771287-c35c6c09-3d15-4a11-bdc3-462fca96c3f8.png)

**Comment by roshaan005** [comment]
If you want and the issue is not fixed yet, I can fix it
